/*
BSD 3-Clause License

Copyright (c) Alliance for Sustainable Energy, LLC. See also https://github.com/NREL/ssc/blob/develop/LICENSE
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __csp_dispatch_ortools_
#define __csp_dispatch_ortools_

#include "base_dispatch_ortools.h"

class csp_dispatch_ortools : public base_dispatch_opt_ortools
{
private:

    operations_research::MPSolverParameters MPsolver_params;

    struct s_continuous_variables {
        std::vector<operations_research::MPVariable*> xr;           // [MWt]     Power delivered by the receiver at time t
        std::vector<operations_research::MPVariable*> xrsu;         // [MWt]     Power used by the receiver for start up
        std::vector<operations_research::MPVariable*> ursu;         // [MWt]     Receiver accumulated start - up thermal power at time t
        std::vector<operations_research::MPVariable*> x;            // [MWt]	 Cycle thermal power consumption at time t
        std::vector<operations_research::MPVariable*> ucsu;         // [MWt]     Cycle accumulated start - up thermal power at time t
        std::vector<operations_research::MPVariable*> wdot;         // [MWe]     Electrical power production at time t
        std::vector<operations_research::MPVariable*> delta_w;      // [MWe]     Positive change in power production at time (t) w/r/t (t-1)
        std::vector<operations_research::MPVariable*> s;            // [MWht]    TES reserve quantity at time t(auxiliary variable)

        // ======= When parallel heater is enabled =========
        std::vector<operations_research::MPVariable*> qeh;          // [MWt]     Thermal power delivered by the electric heaters at time t

        // ======= PV Generation (if applicable) =========
        std::vector<operations_research::MPVariable*> w_pv;         // [MWe]     Electrical power generated by the PV at time t

        void clear() {
            xr.clear();
            xrsu.clear();
            ursu.clear();
            x.clear();
            ucsu.clear();
            s.clear();
            wdot.clear();
            delta_w.clear();
            qeh.clear();
            w_pv.clear();
        }
    } cont_vars;

    struct s_binary_variables {
        std::vector<operations_research::MPVariable*> yr;           // 1 if receiver is generating ``usable'' thermal power at time t; 0 otherwise
        std::vector<operations_research::MPVariable*> yrsu;         // 1 if receiver is starting up at time t; 0 otherwise
        std::vector<operations_research::MPVariable*> yrsup;        // 1 if receiver startup penalty is enforced at time t; 0 otherwise
        std::vector<operations_research::MPVariable*> yrhsp;        // 1 if receiver hot startup penalty is enforced at time t; 0 otherwise
        std::vector<operations_research::MPVariable*> y;            // 1 if cycle is generating electric power at time t; 0 otherwise
        std::vector<operations_research::MPVariable*> ycsu;         // 1 if cycle is starting up at time t; 0 otherwise
        std::vector<operations_research::MPVariable*> ycsup;        // 1 if cycle startup penalty is enforced at time t; 0 otherwise
        // ======= When cycle standby is enabled =========
        std::vector<operations_research::MPVariable*> ycsb;         // 1 if cycle is in standby mode at time t; 0 otherwise
        std::vector<operations_research::MPVariable*> ychsp;        // 1 if cycle hot startup penalty is enforced at time t; 0 otherwise
        std::vector<operations_research::MPVariable*> yoff;         // 1 if cycle is off at time t; 0 otherwise
        // ======= When parallel heater is enabled =========
        std::vector<operations_research::MPVariable*> yeh;          // 1 if electrical heaters are operating at time t; 0 otherwise
        std::vector<operations_research::MPVariable*> yreh;         // 1 if receiver and electrical heaters are operating at time t; 0 otherwise (for defocusing rule)
        std::vector<operations_research::MPVariable*> yhsup;        // 1 if electrical heaters startup cost is enforced at time t; 0 otherwise

        void clear() {
            yr.clear();
            yrsu.clear();
            yrsup.clear();
            yrhsp.clear();
            y.clear();
            ycsu.clear();
            ycsup.clear();
            ycsb.clear();
            ychsp.clear();
            yoff.clear();
            yeh.clear();
            yreh.clear();
            yhsup.clear();
        }
    } bin_vars;

    struct s_constraints {
        // ============== Receiver ====================
        operations_research::MPConstraint* receiver_startup_inventory0;         // only t=0 needs to be updated
        operations_research::MPConstraint* receiver_operation_allowed0;         // only t=0 needs to be updated
        operations_research::MPConstraint* receiver_startup_wait0;              // only t=0 needs to be updated
        operations_research::MPConstraint* receiver_startup_penalty0;           // only t=0 needs to be updated

        std::vector<operations_research::MPConstraint*> receiver_power_limit;
        std::vector<operations_research::MPConstraint*> receiver_production_limit;
        std::vector<operations_research::MPConstraint*> receiver_startup_cut;
        std::vector<operations_research::MPConstraint*> receiver_operation_limit_cut;


        // ============== Electric Heater ====================
        operations_research::MPConstraint* heater_startup_penalty0;             // only t=0 needs to be updated

        std::vector<operations_research::MPConstraint*> heater_off_before_defocus;

        // ============== Power Cycle ====================
        operations_research::MPConstraint* cycle_startup_inventory0;            // only t=0 needs to be updated
        operations_research::MPConstraint* cycle_operation_allowed0;            // only t=0 needs to be updated
        operations_research::MPConstraint* cycle_ramp_up0;                      // only t=0 needs to be updated
        operations_research::MPConstraint* cycle_startup_wait0;                 // only t=0 needs to be updated
        operations_research::MPConstraint* cycle_startup_penalty0;              // only t=0 needs to be updated

        // If cycle standby is enabled
        operations_research::MPConstraint* cycle_standby_persistence0;          // only t=0 needs to be updated
        operations_research::MPConstraint* cycle_standby_startup_penalty0;      // only t=0 needs to be updated

        std::vector<operations_research::MPConstraint*> cycle_production_linearization;
        std::vector<operations_research::MPConstraint*> cycle_sub_hourly_ramp_up;
        std::vector<operations_research::MPConstraint*> cycle_maximum_production;
        std::vector<operations_research::MPConstraint*> cycle_maximum_net_power;

        // ============== Energy Storage ====================
        std::vector<operations_research::MPConstraint*> storage_energy_balance;
        std::vector<operations_research::MPConstraint*> storage_minimum_cycle_operating;

        // ============= PV Generation (if applicable) ==============
        std::vector<operations_research::MPConstraint*> pv_generation_limit;

        void resize(int ntimeints) {
            receiver_power_limit.resize(ntimeints);
            receiver_production_limit.resize(ntimeints);
            receiver_startup_cut.resize(ntimeints);
            receiver_operation_limit_cut.resize(ntimeints);

            heater_off_before_defocus.resize(ntimeints);

            cycle_production_linearization.resize(ntimeints);
            cycle_sub_hourly_ramp_up.resize(ntimeints);
            cycle_maximum_production.resize(ntimeints);
            cycle_maximum_net_power.resize(ntimeints);

            storage_energy_balance.resize(ntimeints);
            storage_minimum_cycle_operating.resize(ntimeints);

            pv_generation_limit.resize(ntimeints);
        }
    } constraints;

    void update_objective_function(unordered_map<std::string, double>& P);

    void update_constraints(unordered_map<std::string, double>& P);

    void build_dispatch_model();

public:

    // Constant parameters
    struct s_params
    {
        // Parameters                       //[units] Description
        double dt;                          //[hr] Time step
        double e_tes_min;                   //[MWht] minimum allowable energy capacity in TES
        double e_tes_max;                   //[MWht] maximum allowable energy capacity in TES
        double e_pb_startup_cold;           //[MWht] energy requirement to start up the power block from cold state
        double e_pb_startup_hot;            //[MWht] energy requirement to start up the power block from standby
        double e_rec_startup;               //[MWht] energy requirement to start up the receiver
        double dt_pb_startup_cold;          //[hr] time requirement to start up the power block from cold state
        double dt_pb_startup_hot;           //[hr] time requirement to start up the power block from hot state
        double dt_rec_startup;              //[hr] time requirement to start up the receiver
        double tes_degrade_rate;            //IN [1/hr] Fractional energy loss from tes per hour
        double q_pb_standby;                //[MWt] power requirement to maintain the power block in standby mode
        double q_pb_des;                    //[MWe] design cycle thermal power input
        double eta_pb_des;                  //[-] design cycle efficiency
        double q_pb_max;                    //[MWt] Maximum allowable thermal energy rate to the cycle
        double q_pb_min;                    //[MWt] Minimum allowable thermal energy rate to the cycle
        double q_rec_min;                   //[MWt] Minimum allowable power delivery by the receiver when operating
        double w_rec_pump;                  //[MWe/MWt] Pumping parasitic power per thermal energy produced

        // Parasitic loads
        double w_rec_ht;			        //[MW-hr] Heat trace power during receiver startup
        double w_track;				        //[MWe] Heliostat tracing power
        double w_stow;				        //[MWe-hr] Heliostat stow electricity requirement
        double w_cycle_pump;		        //[MWe/MWt] Cycle HTF pumping power per thermal energy consumed
        double w_cycle_standby;		        //[MWe] Cycle HTF pumping power during standby

        double inventory_incentive;         //[-]   Terminal storage inventory objective incentive multiplier

        // Heater parameters
        bool is_parallel_heater;            //[-] Is there a heater parallel to the receiver?
        double q_eh_max;                    //[MWt] Maximum allowable power delivery by the electrical heaters when operating
        double q_eh_min;                    //[MWt] Minimum allowable power delivery by the electrical heaters when operating
        double eta_eh;                      //[-] Electric resistance heating sub-system efficiency
        double hsu_cost;                    //[$/start] Heater startup cost

        // PV generation parameters
        bool is_pv_included;                //[-] Is there PV generation within the system?
        double w_pv_max;                    //[MWe] Maximum allowable electrical power generation by the PV
        double pv_op_cost;                  //[$/MWe] PV generation operating cost

        // User-defined parameters
        bool can_cycle_use_standby;         //[-] Can the cycle use standby operation?
        double time_weighting;              //[-] Weighting factor that discounts future decisions over more imminent ones
        double rsu_cost;                    //[$/start] Receiver startup cost
        double csu_cost;                    //[$/start] Cycle startup cost
        double pen_delta_w;                 //[$/MWe-change] Cycle production change penalty
        double q_rec_standby;               //[MWt] Receiver standby thermal power consumption fraction

        s_efftable eff_table_load, eff_table_Tdb, wcondcoef_table_Tdb;  //Efficiency of the power cycle, condenser power coefficients

        s_params() {
            dt = 1.;
            e_tes_min = std::numeric_limits<double>::quiet_NaN();
            e_tes_max = std::numeric_limits<double>::quiet_NaN();
            e_pb_startup_cold = std::numeric_limits<double>::quiet_NaN();
            e_pb_startup_hot = std::numeric_limits<double>::quiet_NaN();
            e_rec_startup = std::numeric_limits<double>::quiet_NaN();
            dt_pb_startup_cold = std::numeric_limits<double>::quiet_NaN();
            dt_pb_startup_hot = std::numeric_limits<double>::quiet_NaN();
            dt_rec_startup = std::numeric_limits<double>::quiet_NaN();
            tes_degrade_rate = std::numeric_limits<double>::quiet_NaN();
            q_pb_standby = std::numeric_limits<double>::quiet_NaN();
            q_pb_des = std::numeric_limits<double>::quiet_NaN();
            eta_pb_des = std::numeric_limits<double>::quiet_NaN();
            q_pb_max = std::numeric_limits<double>::quiet_NaN();
            q_pb_min = std::numeric_limits<double>::quiet_NaN();
            q_rec_min = std::numeric_limits<double>::quiet_NaN();
            w_rec_pump = std::numeric_limits<double>::quiet_NaN();

            can_cycle_use_standby = false;

            time_weighting = 0.99;
            rsu_cost = 952.;
            csu_cost = 10000;
            pen_delta_w = 0.1;
            q_rec_standby = 9.e99;

            is_parallel_heater = false;
            q_eh_max = 0.0;
            q_eh_min = 0.0;
            eta_eh = 1.0;
            hsu_cost = 10.0;

            is_pv_included = false;
            w_pv_max = 0.0;
            pv_op_cost = 0.0;

            w_rec_ht = 0.0;
            w_track = std::numeric_limits<double>::quiet_NaN();
            w_stow = std::numeric_limits<double>::quiet_NaN();
            w_cycle_pump = std::numeric_limits<double>::quiet_NaN();
            w_cycle_standby = std::numeric_limits<double>::quiet_NaN();

            inventory_incentive = 0.;
        }

        void set_user_params(bool cycle_use_standby, double disp_time_weighting,
            double disp_rsu_cost, double disp_hsu_cost, double disp_csu_cost, double disp_pen_delta_w, double disp_inventory_incentive,
            double disp_pv_op_cost, double max_pv_gen, double rec_standby_loss, double rec_heattrace)
        {
            can_cycle_use_standby = cycle_use_standby;
            time_weighting = disp_time_weighting;
            rsu_cost = disp_rsu_cost;
            csu_cost = disp_csu_cost;
            pen_delta_w = disp_pen_delta_w;
            inventory_incentive = disp_inventory_incentive;

            hsu_cost = disp_hsu_cost;

            if (max_pv_gen > 0.0) {
                is_pv_included = true;
                pv_op_cost = disp_pv_op_cost;
                w_pv_max = max_pv_gen;
            }
            else {
                is_pv_included = false;
            }

            q_rec_standby = rec_standby_loss;   //TODO: Update to pull from receiver model
            w_rec_ht = rec_heattrace;           //TODO: Update to pull from receiver model
        }

        void set_user_params(bool cycle_use_standby, double disp_time_weighting,
            double disp_rsu_cost, double disp_hsu_cost, double disp_csu_cost, double disp_pen_delta_w, double disp_inventory_incentive,
            double rec_standby_loss, double rec_heattrace)
        {
            this->set_user_params(cycle_use_standby, disp_time_weighting, disp_rsu_cost, disp_hsu_cost, disp_csu_cost, disp_pen_delta_w,
                disp_inventory_incentive, 0.0, 0.0, rec_standby_loss, rec_heattrace);
        }


        void create_parameter_map(unordered_map<std::string, double>& param_map, int nt);
    } params;

    // Time-series parameters
    struct s_ts_params {
        // Time dependent parameters
        std::vector<double> sell_price;          //[- or $/MWh] Price factor indicating market value of generated energy
        std::vector<double> w_lim;		         //[MWe] Limit on net electricity production
        std::vector<double> q_sfavail_expected;  //Expected available solar field energy
        std::vector<double> eta_pb_expected;     //Expected power cycle conversion efficiency (normalized)
        std::vector<double> w_condf_expected;    //Expected condenser loss coefficient
        std::vector<double> wnet_lim_min;        //minimum expected net power at time t before cycle gross falls before limit
        std::vector<double> delta_rs;            //expected proportion of time step used for receiver start up
        std::vector<double> f_pb_op_limit;		 //[-] Maximum normalized cycle output
        std::vector<double> pv_generation;       //[MWe] Electrical power generated by the PV at time t

        //TODO: This is not used and probably should be removed.
        std::vector<double> eta_sf_expected;     //Expected solar field thermal efficiency (normalized)

        void clear() {
            sell_price.clear();
            w_lim.clear();
            q_sfavail_expected.clear();
            eta_pb_expected.clear();
            w_condf_expected.clear();
            wnet_lim_min.clear();
            delta_rs.clear();
            f_pb_op_limit.clear();
            pv_generation.clear();
            eta_sf_expected.clear();
        }

        void resize(int nt) {
            sell_price.resize(nt);
            w_lim.resize(nt);
            q_sfavail_expected.resize(nt);
            eta_pb_expected.resize(nt);
            w_condf_expected.resize(nt);
            wnet_lim_min.resize(nt);
            delta_rs.resize(nt);
            f_pb_op_limit.resize(nt);
            pv_generation.resize(nt);
            eta_sf_expected.resize(nt);
        }

    } ts_params;

    // Initial conditions
    struct s_init_conditions {
        bool is_rec_operating0;             //receiver is operating at the initial time step
        bool is_rec_starting0;              //receiver is starting up at the initial time step     //TODO: This needs to be updated to reflect the receiver state
        double rec_startup_energy0;         //[MWht] Energy inventory for receiver startup at the initial time step

        bool is_heater_operating0;          //heater is operating at the initial time step

        bool is_pb_starting0;               //Power block is starting up at the initial time step
        bool is_pb_operating0;              //Power block is operating at the initial time step
        bool is_pb_standby0;                //Power block is in standby at the initial time step
        double pb_startup_energy0;          //[MWht] Energy inventory for cycle startup at the initial time step
        double q_pb0;                       //[MWt] Thermal power consumption in the cycle entering the initial time step
        double wdot_pb0;                    //[MWt] Power cycle electric output at the initial time step

        double e_tes0;                      //[MWht] current stored energy capacity

        s_init_conditions() {
            is_rec_operating0 = false;
            is_rec_starting0 = false;
            rec_startup_energy0 = 0.0;

            is_heater_operating0 = false;

            is_pb_starting0 = false;
            is_pb_operating0 = false;
            is_pb_standby0 = false;

            pb_startup_energy0 = 0.0;
            q_pb0 = std::numeric_limits<double>::quiet_NaN();
            wdot_pb0 = std::numeric_limits<double>::quiet_NaN();

            e_tes0 = std::numeric_limits<double>::quiet_NaN();
        };

    } init_conditions;

    // TODO: We might not need this
    struct s_outputs
    {
        std::vector<bool> rec_operation;         // [-] Receiver startup ok?
        std::vector<bool> pb_operation;          // [-] Power block startup ok?
        std::vector<bool> pb_standby;            // [-] Power block standby ok?
        std::vector<double> q_pb_target;         // [MWt] Optimized energy generation (less startup loss)
        std::vector<double> q_pb_standby;        // [MWt] standby energy allowed
        std::vector<double> q_sf_expected;       // [MWt] Expected solar field energy generation
        std::vector<double> tes_charge_expected; // [MWht] Expected thermal energy storage charge state
        std::vector<double> q_pb_startup;        // [MWt] Thermal power going to startup
        std::vector<double> q_rec_startup;       // [MWt] Thermal Power going to startup
        std::vector<double> w_pb_target;         // [MWe] Optimized electricity generation

        std::vector<bool> htr_operation;         // [-] is heater allowed to operate
        std::vector<double> q_eh_target;         // [MWt] Heater target thermal power

        void clear() {
            rec_operation.clear();
            pb_operation.clear();
            pb_standby.clear();
            q_pb_target.clear();
            q_pb_standby.clear();
            q_sf_expected.clear();
            tes_charge_expected.clear();
            q_pb_startup.clear();
            q_rec_startup.clear();
            w_pb_target.clear();

            htr_operation.clear();
            q_eh_target.clear();
        }

        void resize(int nt) {
            rec_operation.resize(nt, false);
            pb_operation.resize(nt, false);
            pb_standby.resize(nt, false);
            q_pb_target.resize(nt, 0.);
            q_pb_standby.resize(nt, 0.);
            q_sf_expected.resize(nt, 0.);
            tes_charge_expected.resize(nt, 0.);
            q_pb_startup.resize(nt, 0.);
            q_rec_startup.resize(nt, 0.);
            w_pb_target.resize(nt, 0.);

            htr_operation.resize(nt, false);
            q_eh_target.resize(nt, 0.);
        }

    } outputs;
    
    //----- public member functions ----

    csp_dispatch_ortools();

    void init(double cycle_q_dot_des, double cycle_eta_des);

    //check parameters and inputs to make sure everything has been set up correctly
    bool check_setup(int nstep);

    //Update parameter values within the horizon
    bool update_horizon_parameters(C_csp_tou &mc_tou);

    // update dispatch initial conditions
    void update_initial_conditions(double q_dot_to_pb, double T_htf_cold_des, double pc_state_persist);

    //Predict performance out nstep values. 
    bool predict_performance(int step_start, int ntimeints, int divs_per_int);    

    

    //declare dispatch function in csp_dispatch.cpp
    bool optimize();

    // Set outputs struct based on solution -> could move to outputs struct
    void set_outputs_from_solution(unordered_map<std::string, double>& params);

    bool set_dispatch_outputs();

    void printResultsFile(std::string filepath, bool append);
};

#endif //__csp_dispatch_ortools_
